//note: as string delimiters please use double quotes only
(function ($) {
    $.localization.addStringBundle("ca", {
		About: "Quant a",
		AcceptTermsMessage: "Accepteu els termes del contracte de llicència abans d'instal·lar Citrix Receiver.",
		AccessGatewayChangePasswordWarning: "Després d'un canvi de contrasenya correcte, cal tancar la sessió. Per utilitzar les aplicacions, torneu a iniciar una sessió.",
		ActivateCitrixPlugin: "Activar el connector de Citrix",
		ActivateCitrixPluginBrowser: "Activeu el connector de Citrix a l'explorador web",
		ActivateReceiver: "Activar...",
		ActivateReceiverToolTip: "Activar Citrix Receiver al vostre escriptori",
		Add: "Agregar",
		AddAll: "Afegeix-ho tot",
		Added: "Agregat",
		AddedToFavorites: "Treure",
		AddFavoritesTitle: "Afegeix preferits",
		AddFavoritesDescription: "Aneu a Escriptoris o Aplicacions, feu clic a Detalls al costat de l'element que vulgueu i seleccioneu Afegeix a preferits.",
		AddFavoritesDescriptionDesktopsOnly: "Aneu a Escriptoris, feu clic a Detalls al costat de l'element que vulgueu i seleccioneu Afegeix a preferits.",
		AddFavoritesDescriptionAppsOnly: "Aneu a Aplicacions, feu clic a Detalls al costat de l'element que vulgueu i seleccioneu Afegeix a favorits.",
		AddFavoritesDescriptionPhone: "Sota el menú, aneu a Escriptoris o Aplicacions, feu clic a Detalls al costat de l'element que voleu i seleccioneu Afegeix a favorits.",
		AddFavoritesDescriptionPhoneDesktopsOnly: "Sota el menú, aneu a Escriptoris, feu clic a Detalls al costat de l'element que vulgueu i seleccioneu Afegeix a preferits.",
		AddFavoritesDescriptionPhoneAppsOnly: "Sota el menú, aneu a Aplicacions, feu clic a Detalls al costat de l'element que voleu i seleccioneu Afegeix a favorits.",
		AddToFavorites: "Afegeix a favorits",
		AllApps: "Aplicacions",
		AllAppsTitle: "Totes les aplicacions",
		AllAppsForToolbar: "Totes",
		AllowPluginToRun: "Permeteu que aquest lloc web executi el connector de Citrix per accedir a les aplicacions.",
		AllRightsReserved: "Reservats tots els drets.",
		AlreadyInstalled: "Ja instal·lat",
		AppDetailsUnavailable: "Detalls de l'aplicació no disponibles",
		AppInMaintenance: "\"{0}\" no està disponible en aquests moments a causa de tasques de manteniment planificades.",
		ApplicationLaunchPlugin: "Plug-in de Citrix per iniciar aplicacions.",
		AppRequestPendingApprovalCannotStart: "\"{0}\" està pendent d'aprovació i no es pot iniciar.",
		Approved: "Aprovat",
		AppStore: "Citrix Receiver",
		AuthFailureSmartcard: "No podeu iniciar sessió usant una targeta intel·ligent.",
		AuthFailureGeneric: "No podeu iniciar sessió en aquest moment.",
		AuthFailurePassthrough: "No es pot iniciar la sessió usant el compte que s'ha utilitzat per iniciar sessió a l'ordinador.",
		Available: "Disponibles",

		Back: "Enrere",
		BackToAppsAndDesktops: "Tornar a aplicacions i escriptoris",
		BlankFolder: "[categoria en blanc]",
		Bundles: "Grups d'aplicacions destacades",
		
		Cancel: "Cancel·lar",
		CancelRequest: "Cancel·lar sol·licitud",
		CannotAddApp: "No es pot afegir l'aplicació \"{0}\".",
		CannotAddAppTitle: "No es pot afegir l'aplicació",
		CannotCompleteYourRequest: "No es pot completar la vostra sol·licitud.",
		CannotDetectReceiverInstallAvailable: "No hem pogut detectar Citrix Receiver. Voleu descarregar-lo i instal·lar-lo?",
		CannotGetYourAppsFromStore: "No es poden obtenir les aplicacions des de la botiga.",
		CannotRemoveApp: "No es pot treure l'aplicació \"{0}\".",
		CannotRemoveAppTitle: "No es pot treure l'aplicació",
		CannotMoveApp: "No es poden reorganitzar les aplicacions perquè el servidor no està disponible.",
		CannotStartApp: "No es pot iniciar l'aplicació \"{0}\".",
		CannotStartDesktop: "No es pot iniciar l'escriptori \"{0}\".",
		CannotStartDesktopSuggestRestart: "No es pot iniciar l'escriptori \"{0}\". Intenteu reiniciar-lo.",
		Categories: "Categories",
		ChangeClient: "Canviar Citrix Receiver...",
		ChangePassword: "Canvia contrasenya...",
		Check: "Comprovar",
		CheckingForUpgrade: "Estem comprovant si hi ha actualitzacions.",
		CheckForUpgrade: "Voleu comprovar si hi ha alguna actualització per a Citrix Receiver?",
		ChromeAppOriginMismatch: "Poseu-vos en contacte amb el vostre departament de TI per donar-vos aquesta informació: Heu de posar l'ID de Citrix Receiver a StoreFront en una llista blanca.",
		ChromePluginHelperMessage: "Permet que el connector de Citrix s'executi en aquest lloc web per accedir a les aplicacions. Per obtenir més informació, consulteu l'article {0} a Citrix Knowledge Center.",
		CitrixCopyright: "2016 Citrix Systems, Inc.",
		CitrixLicenseAgreement: "Contracte de llicència de Citrix",
		ClearSearch: "Esborrar cerca",
		ClickContinue: "feu clic a <strong>Continuar</strong>.",
		ClickInstall: "Instal·lar Citrix Receiver per accedir a les vostres aplicacions",
		ClickUpgrade: "Feu clic a Instal·lar per actualitzar Citrix Receiver",
		Close: "Tancar",
		CloseYourBrowserToEndSession: "Tanqueu el navegador web per tancar la sessió.",
		CloseYourBrowserToProtectAccount: "Tanqueu el navegador web per protegir el vostre compte.",
		ConfirmInstallationIsComplete: "Confirmar instal·lació completada",
		Connect: "Connectar",
		Continue: "Continuar",
		CookiesAreDisabledBody: "Habiliteu les galetes al vostre navegador web abans d'utilitzar aquesta versió de Citrix Receiver",
		CookiesAreDisabledTitle: "Cookies inhabilitades",

		Denied: "Denegat",
		DesktopInMaintenance: "L'escriptori \"{0}\" no està disponible en aquests moments a causa de tasques de manteniment planificades.",
		DesktopRestartWarningText: "Podeu reiniciar l'escriptori per intentar solucionar el problema, però perdreu la feina que no heu desat.",
		DesktopRestartWarningTitle: "Voleu reiniciar l'escriptori \"{0}\"?",
		Desktops: "Escriptoris",
		DetectAgain: "Detectar de nou",
		Details: "Detalls",
		DetectClient: "Detectar client...",
		DetectReceiver: "Detectar Receiver",
		Disconnect: "Desconnectar",
		DisplayInFramesNotAllowed: "Aquest lloc ha estat carregat dins d'una altra pàgina web. Aquesta pàgina s'actualitzarà per tornar a carregar el lloc.",
		DoYouWantToStartApp: "Voleu iniciar \"{0}\"?",
		Download: "Descarregar",
		DownloadUbuntu: "Descarregar per a versions anteriors d'Ubuntu",
		DownloadAgain: "Descarregar de nou",
		DownloadReceiver: "Descarregar Citrix Receiver...",
		DownloadingReceiver: "Descarregant Citrix Receiver...",		
	
		Faq: "Preguntes freqüents",
		Featured: "Destacades",
		Folders: "Carpetes",
		ForFullExperience: "Per a una experiència d'ús òptima, utilitzeu el conjunt complet de funcions inclòs a {0}. Feu clic a Detectar Receiver per començar.",

        GoBackToChoices: "Tornar a les opcions",

        Help: "Ajuda",
		
		IAgreeWith: "Accepto el",
		IfAlreadyInstalled: "Si es detecta Citrix Receiver, veureu una finestra d'aquí a uns segons. Trieu {0}.",
		IfNoWindowAlreadyInstalled: "Si no apareix cap finestra, seleccioneu {0}.",
		IfNoWindowDetectAgain: "Si no apareix cap finestra, feu clic a {0}.",
		IfNoWindowOptions: "Si no apareix cap finestra, seleccioneu alguna de les opcions següents.",
		IfWasInstalled: "Si Citrix Receiver s'ha instal·lat correctament, el navegador web mostrarà una finestra d'aquí a uns segons. Trieu {0}.",
		InfoBarSecurityInformation: "Si permet l'execució del control ActiveX, s'instal·larà un programari a l'ordinador.",
		InProgress: "En curs",
		Install: "Instal·lar",
		InstallationBegins: "Espereu mentre comenceu el procés de descàrrega.",
		InstallReceiver: "Instal·lar Citrix Receiver...",
		InstallWhenDownloadComplete: "Instal·leu Citrix Receiver a la vostra màquina quan completeu la baixada. Un cop instal·lat Citrix Receiver, torneu aquí i feu clic a {0}.",		

		JustAMomentDetecting: "Espereu uns moments, mentre detectem si Citrix Receiver està ja instal·lat.",
		
		LaunchApplication: "Iniciar aplicació",
		Less: "Menys",
		LicenseAgreementContentCode: "CTX_code EP_T_A124358",
		LicenseAgreementContentText: "L'ús d'aquest component està subjecte a la llicència o les condicions de servei de Citrix que cobreixen els productes o serveis de Citrix amb què l'utilitzareu. La llicència d'aquest component només permet utilitzar-lo amb aquests productes o serveis de Citrix.",
		LicenseAgreementContentTitle: "CONTRACTE DE LLICÈNCIA DE CITRIX(R)",
		LoadingContent: "Carregant contingut...",
		LoggingOff: "Tancant la sessió...",
		LoginTimedOut: "La sessió ha superat el temps d'espera per inactivitat.",
		LogOff: "Tancar sessió",
		LogoffError: "Error de tancament de sessió",
		LogOffSessionsFailed: "Si hi ha alguna aplicació que encara s'està executant, surti manualment.",
		LogOn: "Iniciar sessió",
		LogonHasExpired: "La vostra sessió ha caducat. Torneu a iniciar una sessió per continuar.",
		LogonTextPassthrough: "Per utilitzar el compte que heu utilitzat per iniciar sessió a l'ordinador, feu clic a Inicia sessió.",
		LogonTextSmartcard: "Introduïu la vostra targeta intel·ligent al lector i feu clic a Inicia sessió.",

		ManageSecurityQuestions: "Administrar preguntes de seguretat",
		Menu: "Menú",
		More: "Més",
		MultiApprovedApps: "La sol·licitud per afegir aquestes aplicacions ha estat aprovada.",
		MultiDeniedApps: "La sol·licitud per afegir aquestes aplicacions ha estat rebutjada.",

		NoAppsFound: "No hi ha resultats per a la cerca.",
		NoAvailableAuthMethods: "No hi ha mètodes d'inici de sessió disponibles en aquesta plataforma.",
		NoUpdates: "No hi ha actualitzacions disponibles",
		NoUpgradesAvailable: "No hi ha actualitzacions disponibles per a Citrix Receiver.",
		NoWindowDownload: "Si no apareix cap finestra, continueu amb la descàrrega.",

		OK: "Acceptar",
		OnceComplete: "Després d'instal·lar Citrix Receiver, ",
		Open: "Obrir",
		Other: "Altres",
		Overview: "Vista general",

		PartialRefreshFailure: "Alguns servidors no van respondre",
		PasswordExpiresTodayMessage: "La vostra contrasenya caducarà avui.",
		PasswordExpiresTomorrowMessage: "La contrasenya caducarà d'aquí a 1 dia.",
		PasswordExpiryChange: "Canviar ara",
		PasswordExpiryChangeLater: "Ara no",
		PasswordExpiryMessage: "La contrasenya caducarà d'aquí a {0} dies.",
		PasswordExpiryTitle: "Voleu canviar la contrasenya?",
		Pending: "Pendent",
		PendingApproval: "Pendent d'aprovació",
		PhoneOrTabletRequired: "Es requereix telèfon o tauleta",
		PhoneOrTabletRequiredMessage: "Utilitzeu un iPhone, iPad, o un telèfon o tauleta Android per accedir a les seves aplicacions i escriptoris.",
		PleaseLogOnToContinue: "Inicia una sessió per continuar.",
		PopupBlockerDesktopAutoLaunch: "Citrix Receiver ha connectat el vostre escriptori. Per veure'l, habiliteu els elements emergents d'aquest lloc web a l'explorador.",
		PopupBlockerReconnectApps: "Citrix Receiver ha reconnectat les seves aplicacions. Per veure-les, permeteu les finestres emergents d'aquest lloc web a l'explorador.",
		Preferences: "Preferències",
		ProtocolHandlerUpgradeAvailable: "Hi ha una actualització disponible per a Citrix Receiver. Voleu descarregar-la i instal·lar-la?",

		QuickAccess: "Favorits",

		ReceiverForMac: "Citrix Receiver per a Mac",
		ReceiverForWindows: "Citrix Receiver per a Windows",
		Refresh: "Actualitzar",
		RefreshInProgress: "Espereu mentre s'actualitzen les aplicacions.",
		RememberLogonMethod: "Recordar mètode d'inici de sessió",
		Remove: "Treure",
		Request: "Sol·licitar",
		ResumingLogon: "Reprenent l'inici de sessió, espereu.",
		Restart: "Reiniciar",
		ResourceIsNotAvailable: "\"{0}\" no està disponible.",
		RetryDownload: "Reintentar descàrrega",
		RetryEpaLaunch: "Reintentar inici de l'anàlisi EPA",

		SearchAppsPlaceholder: "Cerca en totes les aplicacions",
		SearchDesktopsPlaceholder: "Cerca escriptoris",
		SearchFavoritesPlaceholder: "Cerca a favorits",
		SearchPlaceholder: "Cerca",
		SearchResults: "Resultats de la cerca: ({0})",
		SecurityDetails: "Detalls de seguretat",
		SecurityInformationText: "Quan es descarreguen arxius d'Internet, sempre hi ha riscos de seguretat (poden contenir algun virus o programa que malmeti el seu equip i les dades contingudes en ell). Per comprovar si l'arxiu conté algun tipus d'amenaça de seguretat, feu clic a Instal·lar i després deseu el fitxer en una ubicació adequada de l'equip Abans d'executar o instal·lar el fitxer, analitzeu-lo mitjançant un programa antivirus actualitzat i dueu a terme altres comprovacions necessàries segons el que estableixen les directives de seguretat de la vostra organització. de reconfigurar els paràmetres de seguretat de l'ordinador per instal·lar o executar el fitxer.",
		SecurityInformationTitle: "INFORMACIÓ DE SEGURETAT",
		SessionExpiresInMinutes: "Citrix Receiver excedirà el temps d'espera dins de {0} minuts i {1} segons per inactivitat.",
		SessionExpiresInSeconds: "Citrix Receiver excedirà el temps d'espera dins de {0} segons a causa d'inactivitat.",
		SessionsListFailure: "No es pot iniciar la sessió. Espereu uns minuts i torneu a intentar iniciar la sessió. Si el problema continua, poseu-vos en contacte amb el servei d'assistència tècnica.",
		SessionTimedOut: "La sessió ha superat el temps d'espera per inactivitat.",
		SingleApprovedApp: "La sol·licitud per afegir aquesta aplicació ha estat aprovada.",
		SingleDeniedApp: "La sol·licitud per afegir aquesta aplicació ha estat rebutjada.",
		SkipThisStep: "Feu clic aquí per ometre aquest pas",
		SkipToLogon: "Iniciar sessió",
		SkipToLogonTip: "Feu clic aquí per anar directament a l'inici de sessió",
		SoftwareNotDetected: "Software no detectat",
		SoftwareNotDetectedDetails: "Citrix Receiver no s'ha detectat a l'ordinador. Si esteu segur que Citrix Receiver està instal·lat, feu clic a Continua. Si necessiteu ajuda, poseu-vos en contacte amb el servei d'assistència tècnica.",
		Start: "Iniciar",
		StartApp: "Iniciar aplicació",
		StartAppMessage: "Inicio aquesta aplicació des de la pantalla inicial del telèfon o tauleta.",
		Store: "Botiga",
		SwitchToExplicit: "Canvia a nom d'usuari i contrasenya",
		SwitchToGeneric: "Canvieu a un altre mètode d'autenticació",
		SwitchToSmartcard: "Canviar a targeta intel·ligent",

		Tasks: "Tasques",
		ThirdPartyNotices: "Avisos legals de tercers",
		ThirdPartyNoticesWeb: "Citrix Receiver per a Web",
		ThirdPartyNoticesHtml5: "Citrix Receiver per a HTML5",
		TopRated: "Millors classificats",
		TotalRefreshFailure: "L'actualització ha fallat",
		TryAgain: "Reintentar",
		TryAnotherLogonOption: "Intentar una altra opció d'inici de sessió",
		TryLater: "Intentar-ho més tard",
		TrySearchingInApps: "Intenteu cercar a Aplicacions.",

		UnblockCitrixPlugin: "Desbloquejar el connector de Citrix",
		UnsupportedDevice: "Dispositiu no recolzat",
		UnsupportedDeviceMessage: "Utilitzeu un telèfon, una tauleta o un escriptori recolzats per accedir a les vostres aplicacions i escriptoris.",
		Update: "Actualitzar",
		UpdatedCat: "Actualitzacions disponibles",
		Upgrade: "Actualitzar",
		UpgradeAvailable: "Actualització disponible",
		UpgradeCloseBrowser: "Potser haureu de tancar el navegador web durant el procés d'instal·lació.",
		UpgradeInProgress: "Actualitzant el programari de Citrix Receiver...",
		UpgradeLater: "Actualitzar més tard",
		UpgradeLaterTip: "Feu clic aquí per continuar sense actualitzar Citrix Receiver",
		UseAnotherLogonOption: "Usar una altra opció d'inici de sessió",
		UseChromeApp: "Utilitzeu l'aplicació Citrix Receiver per a Chrome per accedir a aquest lloc",
		UseFullVersion: "Usar versió completa",
		UseLightVersion: "Usar versió simplificada",
		UseReceiver: "Utilitzeu Citrix Receiver per accedir a les vostres aplicacions i escriptoris.",
		UsingFullVersion: "Esteu utilitzant la versió completa de Citrix Receiver. Voleu canviar a la versió simplificada?",
		UsingLightVersion: "Esteu utilitzant la versió simplificada de Citrix Receiver. Voleu canviar a la versió completa?",

		WaitAppInstallMessage: "La vostra aplicació s'instal·larà d'aquí a uns minuts.",
		WaitWhileConfirmInstall: "Espereu mentre confirmem que Citrix Receiver s'ha instal·lat...",
		WebVersion: "Versió Web",
		WelcomeToReceiver: "Benvingut a Citrix Receiver",
		WhenWindowAppearsLaunchApplication: "Quan aparegui una finestra, trieu Inicia l'aplicació.",

		YouCannotUseAppsOrDesktops: "No hi ha aplicacions ni escriptoris disponibles per a vostè en aquest moment.",
		YouCannotUseDesktops: "No hi ha escriptoris disponibles per a vostè en aquest moment.",
		YouCanUseLightVersion: "Si no voleu detectar/instal·lar Citrix Receiver, podeu utilitzar la versió simplificada, amb menys funcions, al vostre navegador web.",
		YouHaveLoggedOff: "La sessió es va tancar correctament.",
		NetscalerGateway: "Citrix Gateway",
		NetscalerAAA: "NetScaler AAA",
		"nsg_username":"Nom d'usuari:",
		"nsg_password1":"Contrasenya:",
		"nsg_password2":"OTC:",
		"nsg_LogOnbutton":"Iniciar la sessió",
		"nsg_loginHeading":"Iniciar una sessió",
		"approve_push":"Aproveu la notificació rebuda al dispositiu registrat",
		"End_User_License_Agreement":"Contracte de llicència d'usuari final",
		"eula_agreement":"Accepto les ",
		"eula_terms":"Termes i condicions",
		"enter_username_msg":"Heu d'introduir el nom per a l'inici de sessió",
		"enter_password_msg":"Heu d'introduir una contrasenya",
		"enter_question_msg":"Heu d'introduir una pregunta personalitzada",
		"enter_answer_msg":"Heu d'introduir totes les respostes",
		"cert_auth_msg_title":"Autenticació amb certificat",
		"epa_title":"Citrix Gateway End Point Analysis",
		"postepa_title":"Citrix Gateway End Point Analysis",
		"Epa_checking_msg":"Comprovant el dispositiu",
		"Epa_Pre_Reqm_Msg":"Abans de connectar amb la xarxa interna de la vostra organització, cal comprovar que el dispositiu compleix certs requisits.",
		"Checking_if_the_plug-in_is_installed":"Comprovant si el connector està instal·lat",
		"epa_download_msg":"No teniu instal·lada la versió més recent d'Endpoint Analysis Plug-in. Utilitzeu l'enllaç per descarregar el plug-in actualitzat",
		"epa_retry_launch_msg":"Si el connector EPA ja està instal·lat, però no s'ha pogut iniciar, feu clic al botó Reintenta l'inici de l'anàlisi EPA per continuar amb l'anàlisi.",
		"epa_retry_after_install_launch_msg":"Feu clic al botó Reintentar inici de l'anàlisi EPA després d'instal·lar el plug-in EPA",
		"epa_undetected_msg":"No hem detectat el connector d'EPA al sistema. Feu clic al botó Descarrega per instal·lar-lo i continuar.",
		"EPAAccessDenied":"Accés denegat",
		"epa_launch_failure_msg":"Endpoint Analysis Plug-in no s'ha iniciat o no està instal·lat. Inicieu-lo o descarregueu-lo amb l'enllaç subministrat.",
		"EPA_not_meet_reqm_msg":"El dispositiu no compleix els requisits per iniciar una sessió.",
		"EPA_MoreInfoMsg":"Per obtenir més informació, poseu-vos en contacte amb el servei d'assistència tècnica i subministreu la informació següent:",
		"EPA_failure_msg":"Va fallar l'anàlisi de seguretat de punt final",
		"epa_v2_failure_msg":"Error d'Endpoint Analysis. Contacteu amb el vostre administrador amb l'ID següent",
		"Epa_Progress_Msg":"Anàlisi EPA en curs",
		"Skip Check":"Ometre comprovació",
		"user_skip_epa_msg":"L'usuari va ometre l'anàlisi",
		"Date":"Data: ",
		"Time":"Hora: ",
		"EPAMessaage":"Missatge: ",
		"secs":"seg",
		"TryAgain":"Reintentar",
		"Intranet_IP_Address":"Adreça IP d'Intranet",
		"Idle_Time":"Temps d'inactivitat (H:MM:SS)",
		"nsg_GoBack":"Tornar",
		"nsg-tlogin-heading":"Transferir inici de sessió",
		"nsg-tlogin-transfer":"Transferir",
		"nsg-tlogin-cancel":"Cancel·lar",
		"tlogin_single_res":"Té una sessió iniciada a Citrix Gateway en un altre dispositiu. Voleu finalitzar aquesta sessió?",
		"tlogin_multi_res1":"Ha arribat al límit de les sessions Citrix Gateway permeses.",
		"tlogin_multi_res2":"Seleccioneu quina sessió finalitzar per continuar amb aquesta sessió.",
		"tlogin_cancel_title":"Heu triat cancel·lar la transferència de l'inici de sessió. Feu clic al botó de sota per tornar a iniciar una sessió.",
		"LicenseError":"Error: L'inici de sessió supera el nombre màxim d'usuaris permesos.",
		"NoIIP":"Cap IP d'Intranet disponible. Intenteu iniciar sessió més tard.",
		"GenericError":"El servidor ha trobat un error. Torneu-ho a provar o poseu-vos en contacte amb l'administrador.",
		"Network_Access": "Accés de xarxa",
		"Connect_with_the_AG_Plugin": "Connectar-se amb Citrix Gateway Plug-in",
		"Connect_with_the_AG_Plugin_for_MAC": "Connectar-vos amb Citrix Gateway Plug-in per a MAC",
		"Clientless_Access": "Accés sense client",		
		"Citrix_XenApp": "Accés a escriptoris i aplicacions virtuals",
		"agent_description": "Permet accedir als recursos de la vostra organització des del dispositiu a través d'un client VPN complet. Se us demanarà que instal·leu el plug-in, si encara no en teniu. Utilitzeu aquesta opció només si esteu usant un dispositiu de confiança.",
		"cvpn_description": "Seleccioneu el mode d'accés sense client per accedir als recursos mitjançant un navegador web. L'accés segur es limita a la finestra del navegador amb què va iniciar una sessió a la VPN. Utilitzeu aquesta opció si utilitzeu un dispositiu que no és de confiança.",
		"ica_description": "Seleccioneu aquesta opció per accedir a les vostres aplicacions i escriptoris virtuals de l'empresa amb Citrix Receiver.",
		"ClientchoicesTitle": "Seleccioneu una d'aquestes opcions:",
		"Citrix_Access_Gateway": "Citrix Gateway",
		"If_the_Access_Gateway_Plugin_is_installed": "Si Citrix Gateway Plug-in està instal·lat però no s'està executant, feu clic a \"Inici &amp;gt; Tots els programes &amp;gt; Citrix &amp;gt; Citrix Gateway\" per iniciar l'aplicació.",
		"vpn_waitingmsg": "Espereu que s'estableixi la sessió VPN.",
		"If_a_proxy_server_is_configured": "Si hi ha un servidor intermediari configurat, heu d'afegir \"localhost\" a excepció del servidor intermediari al navegador web.",
		"For_more_information_contact_your_help_desk_or_system_administrator": "Per obtenir més informació, poseu-vos en contacte amb el servei d'assistència tècnica o amb l'administrador del sistema.",
		"To_install_the_Access_Gateway_Plugin": "Per instal·lar Citrix Gateway Plug-in:",
		"Click_Download": "1. Feu clic a <B>Descarregar<B>.",
		"To_install_the_Netscaler_Access_Gateway_Client_for_Linux":"Per instal·lar Citrix Gateway Client per a Linux (recolzat actualment al SO Ubuntu)",
		"If_the_Access_Gateway_Plug-in_is_not_installed":"Citrix Gateway Plug-in no està instal·lat, o cal actualitzar-lo.",
		"To_install_the_Netscaler_Access_Gateway_Client_for_Mac":"Descarregueu i executeu el programa d'instal·lació del connector. El connector es connecta automàticament després de la instal·lació.",
		"Linux_install_using_software_center":"2. Instal·leu el paquet debian descarregat usant el Centre de programari d'Ubuntu",
		"In_the_File_Download_dialog_box_click_Run": "2. Al quadre de diàleg Descàrrega del fitxer, feu clic a <B>Executar</B>.",
		"In_the_Internet_Explorer_dialog_box_click_Run_to_install_the_Access_Gateway_Plugin_for_Windows": "3. Al quadre de diàleg del navegador web, feu clic a <B>Executar</B> per instal·lar Citrix Gateway Plug-in per a Windows.",
		"cvpn_wait_msg":"Carregant aplicacions...",
		"RDP_hint" : "Cal marcar la casella 'Enllaç RDP', en cas que s'afegeixi o s'accedeixi a un enllaç RDP amb el botó Anar.",
		"PB_url":"URL<sup>*</sup>:",
		"PB_name":"Nom<sup>*</sup>:",
		"PB_description":"Descripció:",
		"Enter_url_placeholder":"Introduir URL",
		"Enter_name_placeholder":"Trieu un nom",
		"Enter_description_placeholder":"Afegeix una descripció",
		"save":"Guardar",
		"Go":"Anar",
		"Delet":"Eliminar",
		"Bookmark":"Marcador",
		"rdplinkChecklabel":"Enllaç RDP",
		"Allow_popups":"Permet les finestres emergents al vostre navegador web per veure la URL en una pestanya nova.",
		"Personal_Bookmark":"Marcador personal",
		"PersonalBookmark_error1" : "Heu de proporcionar un URL per al vostre marcador.",
		"PersonalBookmark_error2" : "Introduïu un nom per al marcador.",
		"PersonalBookmark_error3" : "El marcador conté caràcters URI no vàlids. Introduïu una adreça web vàlida.",
		"NsgEmail_AppName":"Servidor de correu",
		"PersonalBookmark_error4":"Introduïu un URL primer.",
		"errorMessageLabel4444":"Credencials incorrectes. Torneu-ho a provar.",
		"errorMessageLabel4001":"Credencials incorrectes. Torneu-ho a provar.",
		"errorMessageLabel4002":"No teniu permís per iniciar la sessió.",
		"errorMessageLabel4003":"No es pot connectar amb el servidor. Torneu a intentar connectar d'aquí a uns minuts.",
		"errorMessageLabel4004":"No es pot connectar. Torneu-ho a provar.",
		"errorMessageLabel4005":"No es pot connectar. Torneu-ho a provar.",
		"errorMessageLabel4006":"Nom d'usuari incorrecte.",
		"errorMessageLabel4007":"Contrasenya incorrecta.",
		"errorMessageLabel4008":"Les contrasenyes no coincideixen.",		
		"errorMessageLabel4009":"Usuari no trobat.",
		"errorMessageLabel4010":"No teniu permís per iniciar la sessió en aquest moment.",
		"errorMessageLabel4011":"El vostre compte està inhabilitat.",
		"errorMessageLabel4012":"La contrasenya ha caducat.",
		"errorMessageLabel4013":"No teniu permís per iniciar la sessió.",
		"errorMessageLabel4014":"No s'ha pogut canviar la contrasenya.",
		"errorMessageLabel4015":"El vostre compte està temporalment bloquejat.",
		"errorMessageLabel4016":"No s'ha pogut actualitzar la contrasenya. La contrasenya ha de complir els requisits de longitud, complexitat i historial del domini.",
		"Admin_apps_bundle_descr":"Aplicacions lliurades per Gateway",
		"Admin_apps_bundle_title":"Aplicacions Web i SaaS",
		"Personal_apps_bundle_descr":"Marcadors web personals",
		"Personal_apps_bundle_title":"Marcadors personals",
		"Admin_apps_title":"Marcadors de Citrix Gateway",
		"Personal_apps_title":"Marcadors personals",
		"vmware_bundle_descr":"Aplicacions de VMware",
		"vmware_bundle_title":"Aplicacions VMware",
		"vmware_apps_title":"Aplicacions VMware",
		"vmware_missing_title":"Falta el client VMware",
		"vmware_install_reqd_msg":"Instal·leu VMware Horizon Client",
		"MaxLoginAttempts":"Ha superat el màxim d'intents d'inici de sessió.",
		"NoClientChoices":"No hi ha cap manera d'accés disponible per a vostè en aquest moment. Contacteu amb el vostre servei d'assistència tècnica",
		"NoPrimaryAuthPol":"No s'ha trobat una directiva activa a la cascada d'autenticació principal. Contacteu amb el servei d'assistència tècnica",
		"NoSecondaryAuthPol":"No s'ha trobat una directiva activa a la cascada d'autenticació secundària. Contacteu amb el servei d'assistència tècnica",
		"NoTertiaryAuthPol":"No s'ha trobat una directiva activa a la cascada d'autenticació terciària. Contacteu amb el servei d'assistència tècnica",
		"IncorrectCapabilities":"El client no pot connectar amb aquest servidor. Contacteu amb el servei d'assistència tècnica",
		/* OTP Management Messages */
		"Done": "List",
		"OTPDeleteAllSuccess": "S'han eliminat correctament tots els dispositius registrats",
		"OTPDeleteAllFailure": "No s'ha pogut eliminar tots els dispositius",
		"OTPDeleteDeviceSuccess" : "{0} eliminat correctament",
		"OTPDeleteDeviceFailure" : "No s'ha pogut suprimir {0}",
		"OTPConfirmDelete" : "Confirmar eliminació",
		"Yes": "Sí",
		"No": "No",
		"OTPDeleteAllConfirm": "Segur que voleu eliminar TOTS els dispositius registrats?",
		"OTPDeleteDeviceConfirm": "Segur que voleu suprimir {0}?",
		"OTPCode": "Escanegeu el codi QR o escriviu el codi {0}",
		"OTPAddSuccess": "{0} s'ha afegit correctament",
		"OTPAddFailure": "No s'ha pogut afegir {0}",
		"OTPDeviceExists": "El dispositiu '{0}' ja existeix",
		"OTPEnterName": "Introduïu un nom de dispositiu per afegir",
		"OTPTestSuccess": "Contrasenya OTP verificada correctament des de {0}",
		"OTPTestFailure": "No s'ha pogut verificar el PIN d'ús únic de {0}. Assegureu-vos que Citrix ADC està sincronitzat amb l'hora NTP.",
		"OTPEnterTestValue": "Introduïu el valor de la contrasenya OTP per provar",
		"OTPDeleteAll": "Eliminar TOT",
		"OTPAddDeviceToolTip": "Afegeix dispositiu",
		"OTPTestDeviceToolTip": "Provar dispositiu",
		"OTPRegisteredDevices": "Els meus dispositius registrats",
		"OTPNoDevices": "No hi ha dispositius registrats",
		"OTPTest": "Provar",
		"OTPQRError":"No s'ha pogut carregar ReCaptcha. Poseu-vos en contacte amb el vostre administrador.",
		"OTPAddMaxDevices":"Ha arribat a la quantitat màxima de dispositius permesos.",

		
        /* OTP Management Messages End*/
	/* nFactor messages begin */
	"Invalid Credentials": "Credencials no vàlides",
	"Not Permitted": "No permès",
	"System Timeout": "Temps d'espera del sistema esgotat",
	"System Error": "Error del sistema",
	"Socket Error": "Error de socket",
	"Bad User": "Usuari incorrecte",
	"Bad Password": "Contrasenya incorrecta",
	"Password Mismatch": "Les contrasenyes no coincideixen",
	"No such user": "Aquest usuari no existeix",
	"Restricted Hours": "Horari restringit",
	"Account Disabled": "Compte inhabilitat",
	"Password Expired": "Contrasenya caducada",
	"No dial-in permission": "No hi ha permís d'accés telefònic",
	"Changing Password": "Canviant contrasenya",
	"Account Locked": "Compte bloquejat",
	"Constraint violation": "Infracció de restricció",
	"Try again after some time or contact your help desk": "Torneu-ho a provar en uns instants o poseu-vos en contacte amb el servei d'assistència",
	"Certificate not presented by user": "Certificat no presentat per l'usuari",
	"Renegotiation of certificate failed": "Ha fallat la renegociació del certificat",
	"Invalid certificate is presented": "Es va presentar un certificat no vàlid",
	"Error trying to extract artifact from certificate": "Error en intentar extreure l'artefacte del certificat",
	"No active policy during authentication": "Cap directiva no estava activa durant l'autenticació",
	"No active policy while trying to fallback from certificate failure": "No s'ha trobat una directiva activa en cercar una alternativa a la decisió de certificat",
	"No active policy while trying to fallback from Negotiate/NTLM failure": "No s'ha trobat una directiva activa en cercar una alternativa per a la fallada de Negotiate/NTLM",
	"You are not allowed to login. Please contact administrator": "No teniu permís per iniciar sessió. Poseu-vos en contacte amb l'administrador",
	"You have exceeded the maximum login attempts. Please contact administrator": "Heu excedit el nombre màxim d'intents d'inici de sessió. Poseu-vos en contacte amb l'administrador",
	"Netscaler unable to contact server for NTLM authentication. Please contact administrator": "Citrix ADC no pot contactar amb un servidor per a l'autenticació NTLM. Poseu-vos en contacte amb l'administrador",
	"Target URL not found for redirect after successful login. Please contact your administrator.": "No s'ha trobat l'URL de destinació per redirigir-lo després de l'inici de sessió correcte. Poseu-vos en contacte amb l'administrador.",
	"EPA Factor is mutually exclusive with EPA at vserver": "El factor EPA i l'EPA a vserver s'exclouen mútuament",
	"No active policy to begin EPA": "No hi ha una directiva activa per començar l'EPA",
	"Session absent to manage otp for user, probably misconfiguration. Please contact your adminsitrator.": "No es troba la sessió per administrar OTP per a l'usuari. Pot ser un error de configuració. Poseu-vos en contacte amb l'administrador.",
	/* nFactor messages end */
	"nsg_oldpass": "Contrasenya anterior:",
	"nsg_newpass": "Nova contrasenya:",
	"nsg_confirmpass": "Confirma la contrasenya:",
	"nsg_changepass": "Canvi de contrasenya",
	"ns_dialogue": "Contrasenya",
	"ns_DialogSubmit": "Enviar",
	"Password change failed. Make sure you supply correct existing password and try again.": "El canvi de contrasenya ha fallat. Assegureu-vos d'introduir la contrasenya actual correctament i torneu-ho a provar.",
	"Gateway encountered an unexpected condition. Please contact your admin for details": "Citrix Gateway ha trobat una condició inesperada. Poseu-vos en contacte amb el vostre administrador per obtenir més informació",
	"You are not allowed to change the password. Please contact your admin for details.": "No teniu permís per canviar la contrasenya. Poseu-vos en contacte amb el vostre administrador per obtenir més informació.",
	"One of the fields is empty. Please enter your password, and new password twice.": "Un dels camps és buit. Introduïu la contrasenya i la nova contrasenya dues vegades.",
	"The passwords you typed do not match. Please try again.": "Les contrasenyes que heu introduït no coincideixen. Torna a intentar-ho.",


    // Login schema localisation changes
	"checkbox_accept_terms_and_conditions": "Acceptar termes i condicions",
	"checkbox_log_on": "Iniciar sessió",
	"checkbox_password": "Contrasenya:",
	"checkbox_please_enter_username": "Introduïu un nom d'usuari",
	"checkbox_user_name": "Nom d'usuari:",
	"clientcertdualauthdeviceid_": "",
	"clientcertdualauthdeviceid_passcode": "Codi d'accés:",
	"clientcertdualauthdeviceid_password": "Contrasenya:",
	"clientcertdualauthdeviceid_please_log_on": "Inicia una sessió",
	"clientcertdualauthdeviceid_remember_my_credentials": "Recordar les meves credencials",
	"clientcertdualauthdeviceid_submit": "Enviar",
	"clientcertdualauthdeviceid_user_name": "Nom d'usuari:",
	"clientcertsingleauthdeviceid_first_factor": "Primer factor",
	"clientcertsingleauthdeviceid_log_on": "Iniciar sessió",
	"clientcertsingleauthdeviceid_password": "Contrasenya:",
	"clientcertsingleauthdeviceid_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"clientcertsingleauthdeviceid_remember_my_password": "Recordar contrasenya",
	"clientcertsingleauthdeviceid_user_name": "Nom d'usuari:",
	"domaindropdown_(select_a_domain)": "(Seleccioneu un domini)",
	"domaindropdown_aaatm.com": "AAATM.COM",
	"domaindropdown_log_on": "Iniciar sessió",
	"domaindropdown_nsi-test.com": "NSI-TEST.COM",
	"domaindropdown_password": "Contrasenya:",
	"domaindropdown_please_select_domain_to_continue_login_...": " Seleccioneu un domini per continuar amb l'inici de sessió...",
	"domaindropdown_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"domaindropdown_user_name": "Nom d'usuari:",
	"dualauth_": "",
	"dualauth_flipped_": "",
	"dualauth_flipped_passcode": "Codi d'accés:",
	"dualauth_flipped_password": "Contrasenya:",
	"dualauth_flipped_please_log_on": "Inicia una sessió",
	"dualauth_flipped_remember_my_credentials": "Recordar les meves credencials",
	"dualauth_flipped_submit": "Enviar",
	"dualauth_flipped_user_name": "Nom d'usuari:",
	"dualauth_passcode": "Codi d'accés:",
	"dualauth_password": "Contrasenya:",
	"dualauth_please_log_on": "Inicia una sessió",
	"dualauth_remember_my_credentials": "Recordar les meves credencials",
	"dualauth_submit": "Enviar",
	"dualauth_user_name": "Nom d'usuari:",
	"dualauthdeviceid_": "",
	"dualauthdeviceid_passcode": "Codi d'accés:",
	"dualauthdeviceid_password": "Contrasenya:",
	"dualauthdeviceid_please_log_on": "Inicia una sessió",
	"dualauthdeviceid_remember_my_credentials": "Recordar les meves credencials",
	"dualauthdeviceid_submit": "Enviar",
	"dualauthdeviceid_user_name": "Nom d'usuari:",
	"dualauthorotpregisterdynamic_": "",
	"dualauthorotpregisterdynamic_click_to_register": "Feu clic per registrar-se",
	"dualauthorotpregisterdynamic_devicename": "Nom del dispositiu:",
	"dualauthorotpregisterdynamic_passcode": "Codi d'accés:",
	"dualauthorotpregisterdynamic_password": "Contrasenya:",
	"dualauthorotpregisterdynamic_please_log_on": "Inicia una sessió",
	"dualauthorotpregisterdynamic_remember_my_credentials": "Recordar les meves credencials",
	"dualauthorotpregisterdynamic_submit": "Enviar",
	"dualauthorotpregisterdynamic_user_name": "Nom d'usuari:",
	"dualauthorpush_please_log_on": "Inicia una sessió",
	"dualauthorpush_user_name": "Nom d'usuari:",
	"dualauthorpush_password": "Contrasenya:",
	"dualauthorpush_vip_or_totp": "VIP o TOTP:",
	"dualauthorpush_click_to_use_push": "Feu clic per utilitzar push",
	"dualauthorpush_submit": "Enviar",
	"onlydomaindropdown_(select_a_domain)": "(Seleccioneu un domini)",
	"onlydomaindropdown_aaatm.com": "AAATM.COM",
	"onlydomaindropdown_citrix.com": "CITRIX.COM",
	"onlydomaindropdown_log_on": "Iniciar sessió",
	"onlydomaindropdown_nsi-test.com": "NSI-TEST.COM",
	"onlydomaindropdown_please_select_domain_to_continue_login_...": " Seleccioneu un domini per continuar amb l'inici de sessió...",
	"onlyotpregistration_device_name_for_managing_secret": "Nom del dispositiu per administrar el secret",
	"onlyotpregistration_mobile": "mòbil",
	"onlyotpregistration_devicename": "Nom del dispositiu:",
	"onlyotpregistration_please_log_on": "Inicia una sessió",
	"onlyotpregistration_submit": "Enviar",
	"onlyotpregistration_user_name": "Nom d'usuari:",
	"onlypassword_please_enter_password_for_step_up_auth":" Introduïu la contrasenya per configurar l'autenticació.",
	"onlypassword_hello":"Hola, ",
	"onlypassword_hello_please_enter_password_for_step_up_auth": "Hola, Introduïu la contrasenya per a l'autenticació per passos.",
	"onlypassword_log_on": "Iniciar sessió",  
	"onlypassword_password": "Contrasenya:",
	"onlypassword_remember_my_password": "Recordar contrasenya",
	"onlyusername_log_on": "Iniciar sessió",
	"onlyusername_please_enter_username_...": " Introduïu un nom d'usuari...",
	"onlyusername_please_supply_either_username_as_saamaccountname": "Introduïu el nom d'usuari com a nom de compte SAM",
	"onlyusername_remember_my_password": "Recordar contrasenya",
	"onlyusername_user_name": "Nom d'usuari:",
	"pass_enc_encryption_failed_header":"Error al xifratge de contrasenya",
	"pass_enc_encryption_failed_message":"Error al xifratge de contrasenya. Per continuar amb l'inici de sessió, inhabiliteu el xifratge de contrasenyes.",
	"pass_enc_unsupported_browser_header":"Explorador no compatible per a xifratge",
	"pass_enc_unsupported_browser_message":"El xifratge de contrasenyes no és compatible amb el vostre navegador. Per obtenir la llista de navegadors i versions que admeten xifratge de contrasenyes, consulteu la documentació de Citrix",
	"prefiluserfromexpr_log_on": "Iniciar sessió",
	"prefiluserfromexpr_password": "Contrasenya:",
	"prefiluserfromexpr_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"prefiluserfromexpr_remember_my_password": "Recordar contrasenya",
	"prefiluserfromexpr_second_factor": "Segon factor",
	"prefiluserfromexpr_user_name": "Nom d'usuari:",
	"singleauth_first_factor": "Primer factor",
	"singleauth_log_on": "Iniciar sessió",
	"singleauth_password": "Contrasenya:",
	"singleauth_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"singleauth_remember_my_password": "Recordar contrasenya",
	"singleauth_user_name": "Nom d'usuari:",
	"singleauthcaptcha_captcha": "Captcha:",
	"singleauthcaptcha_log_on": "Iniciar sessió",
	"singleauthcaptcha_password": "Contrasenya:",
	"singleauthcaptcha_please_enter_your_credentials_and_verify_captcha": "Introduïu les vostres credencials i verifiqueu-vos amb el captcha",
	"singleauthcaptcha_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"singleauthcaptcha_remember_my_password": "Recordar contrasenya",
	"singleauthcaptcha_user_name": "Nom d'usuari:",
	"dualauthcaptcha_captcha": "Captcha:",
	"dualauthcaptcha_log_on": "Iniciar sessió",
	"dualauthcaptcha_password": "Contrasenya:",
	"dualauthcaptcha_passcode": "Codi d'accés:",
	"dualauthcaptcha_please_enter_your_credentials_and_verify_captcha": "Introduïu les vostres credencials i verifiqueu-vos amb el captcha",
	"dualauthcaptcha_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"dualauthcaptcha_remember_my_password": "Recordar contrasenya",
	"dualauthcaptcha_user_name": "Nom d'usuari:",
	"singleauthdeviceid_first_factor": "Primer factor",
	"singleauthdeviceid_log_on": "Inicia la sessió",
	"singleauthdeviceid_password": "Contrasenya:",
	"singleauthdeviceid_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Introduïu domini\\nomUsuari o usuari@nom.domini.complet",
	"singleauthdeviceid_remember_my_password": "Recordar contrasenya",
	"singleauthdeviceid_user_name": "Nom d'usuari:",
	"singleauthmanageotp_password": "Contrasenya:",
	"singleauthmanageotp_please_log_on": "Inicia una sessió",
	"singleauthmanageotp_submit": "Enviar",  
	"singleauthmanageotp_user_name": "Nom d'usuari:",
	"singleauthdopush_please_logon": "Inicia una sessió",
	"singleauthdopush_username": "Nom d'usuari:",
	"singleauthdopush_password": "Contrasenya:",
	"singleauthdopush_submit": "Enviar",
	"singleauthpasswordreset_first_factor": "Primer factor",
	"singleauthpasswordreset_submit": "Enviar",
	"singleauthpasswordreset_password": "Contrasenya:",
	"singleauthpasswordreset_please_supply_either_domain\\username_or_user@fully.qualified.domain": "Domini\\usuari o usuari@domini.com",
	"singleauthpasswordreset_remember_my_password": "Recordar contrasenya",
	"singleauthpasswordreset_user_name": "Nom d'usuari:",
	"singleauthpasswordreset_forgot_password": "Contrasenya oblidada",
	"dualauthpasswordreset_": "",
	"dualauthpasswordreset_passcode": "Codi d'accés:",
	"dualauthpasswordreset_password": "Contrasenya:",
	"dualauthpasswordreset_please_log_on": "Inicia una sessió",
	"dualauthpasswordreset_remember_my_credentials": "Recordar les meves credencials",
	"dualauthpasswordreset_submit": "Enviar",
	"dualauthpasswordreset_user_name": "Nom d'usuari:",
	"dualauthpasswordreset_forgot_password": "Contrasenya oblidada",
	"ForgotPassword" : "Contrasenya oblidada",
	"waitMessage" : "La vostra sol·licitud s'està processant",
	"sspr_password_reset_successful" : "La contrasenya es va restablir correctament",
	"nsg_kba_registration_heading" : "Registre KBA",
	"email_registration_heading" : "Registre de correu electrònic",
	"alternate_email_id" : "ID alternatiu de correu electrònic",
	"EmailOTP" : "Introduir contrasenya OTP rebuda per correu electrònic",
	"kba_invalide_qora" : "Pregunta/resposta no vàlida",
	"emailotp_invalid_code" : "Contrasenya OTP no vàlida. L'autenticació per email ha fallat; No hi ha més accions per continuar.",
	"nsg_kba_question" : "Pregunta",
	"nsg_kba_answer" : "Resposta",
	"dualauthpushorotp_please_log_on": "Inicia una sessió",
	"dualauthpushorotp_user_name": "Nom d'usuari:",
	"dualauthpushorotp_password": "Contrasenya:",
	"dualauthpushorotp_vip_or_totp": "VIP o OTP:",
	"dualauthpushorotp_click_to_use_otp": "Feu clic per introduir la contrasenya d'un sol ús (OTP) manualment",
	"dualauthpushorotp_submit": "Enviar",
	"KB Questions and Answers not registered":"Preguntes i respostes de KB no registrades",
	"Question":"Pregunta",
	"Answer":"Resposta",
	"OTPDeleteDevice":"Escanegeu el codi QR a l'aplicació Citrix SSO"
    });
})(jQuery);
